### PR TITLE
Add indexing to Auxiliary events

### PR DESCRIPTION
**Pull request by EndymionJkb**
# Description

Add indexing to VaultAuxiliary events. And change the key to bytes32 so that it can also be indexed.

I recall some discussion about this (not sure of the context). I don't think we care too much about the efficiency of this event (expected to be used by aggregators), but it doesn't seem to hurt anything.

If we want to keep the string key for some reason, it would be possible to retain that and only index the pool.

## Type of change

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [X] Code refactor / cleanup
- [ ] Optimization: [ ] gas / [ ] bytecode
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [X] The diff is legible and has no extraneous changes
- [N/A] Complex code has been commented, including external interfaces
- [ ] Tests have 100% code coverage
- [X] The base branch is either `main`, or there's a description of how to merge

### CODE REVIEW

**Review by joaobrunoah — APPROVED** [review]
LGTM!

**Review by jubeira — COMMENTED** [review]
@johngrantuk here's an alternative version of the auxiliary event you've proposed.

I think it makes sense; 32 bytes should be OK for the event key, and having the arguments indexed might be useful. WDYT? Deferring final approval to you.

**Comment by EndymionJkb** [comment]
This was motivated by an audit finding.

**Comment by johngrantuk** [comment]
This was the original feedback from Daniel:
dont think we care about indexing, and these will be primarily admin related functions, so not gas sensitive
the idea is the pool will also emit a more readable version of the event, this event is for ease of integration for aggregators

I also agreed with that but don't see a big problem if we really want to change. Main issue I see is aggregators are currently working on deploy11 and this would be a change they need to handle on launch.

**Review by johngrantuk — APPROVED** [review]

**Pull request merged**
